### PR TITLE
changed params to read them at runtime

### LINKED ISSUE #33: [Bug]: useSsl parameter does not work
### Describe the bug

The `useSsl` parameter is always false irrespective of the input parameter value.

### To reproduce

set the `--parameter useSsl=true` and output the value of `useSsl` flag value. The value will be false.

### Expected behavior

The value of the `useSsl` boolean value should be set according to the parameter value.

### Host / Environment

_No response_

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by abhinavGupta16**
Signed-off-by: Abhinav Gupta <abhng@amazon.com>

### Description
The parameters were not resolved at runtime and therefore, the boolean variables were never set(always false)
 
### Issues Resolved
#33 

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: lib/ci-stack.ts [hunk 1]
```diff
@@ -33,19 +33,11 @@ export class CIStack extends Stack {
...
-
-    const runWithOidcParameter = new CfnParameter(this, 'runWithOidc', {
-      description: 'If the jenkins instance should use OIDC + federate',
-      allowedValues: ['true', 'false'],
-    });
-
-    const useSsl = useSslParameter.valueAsString === 'true';
-    const runWithOidc = runWithOidcParameter.valueAsString === 'true';
+    const runWithOidcParameter = this.node.tryGetContext('runWithOidc');
+    const runWithOidc = runWithOidcParameter === 'true';
```
Comment (gaiksaya) [inline lib/ci-stack.ts:40]: Glad it worked!
You need to add checks if the values entered by user is either true or false. CfnParameters does that by using `allowedValues`, for context variables we need to add checks AFAIK

Comment (abhinavGupta16) [reply lib/ci-stack.ts:40]: Is that provision allowed with tryGetContext()? CfnParameters could not be used since we needed the actual values at runtime.

**Review by peternied — COMMENTED** [review]
Great work around and I love the simplicity for the command line.  When we deploy the stack, how can you track these values are set in one manner or another?

One possibility, keep the parameters but we default the value as from the cdk context so they are still recorded and would show up in a stack diff before deployment

**Review by peternied — APPROVED** [review]

File: lib/ci-stack.ts [hunk 2]
```diff
@@ -33,19 +33,31 @@ export class CIStack extends Stack {
       },
     });
 
-    const useSslParameter = new CfnParameter(this, 'useSsl', {
-      description: 'If the jenkins instance should be access via SSL',
-      allowedValues: ['true', 'false'],
+    const useSslParameter = this.node.tryGetContext('useSsl');
+    if (useSslParameter !== 'true' && useSslParameter !== 'false') {
+      throw new ReferenceError('useSsl parameter is required to be set as "true" or "false"');
```
Comment (gaiksaya) [inline lib/ci-stack.ts:38]: Do we need to mention the quotes `"` as well? If not remove it. Just true or false seems fine

Comment (abhinavGupta16) [reply lib/ci-stack.ts:38]: I put quotes to emphasize on the 2 values that are acceptable.

Comment (gaiksaya) [reply lib/ci-stack.ts:38]: I think its understandable when you say it should be either true or false. The user should not get confused as to add the quotes and still see the error. Lets be clear :)

File: lib/ci-stack.ts [hunk 3]
```diff
@@ -34,9 +34,17 @@ export class CIStack extends Stack {
...
     const useSslParameter = this.node.tryGetContext('useSsl');
+    if (useSslParameter !== 'true' && useSslParameter !== 'false') {
+      throw new ReferenceError('useSsl parameter is required to be set as "true" or "false"');
+    }
+
     const useSsl = useSslParameter === 'true';
 
     const runWithOidcParameter = this.node.tryGetContext('runWithOidc');
+    if (runWithOidcParameter !== 'true' && runWithOidcParameter !== 'false') {
+      throw new ReferenceError('runWithOidc parameter is required to be set as "true" or "false"');
```
Comment (peternied) [inline lib/ci-stack.ts:45]: Why use `ReferenceError`, just make this an `Error` type unless there is something like an argument error

Comment (abhinavGupta16) [reply lib/ci-stack.ts:45]: I actually used `Error` before and then later changed to `ReferenceError` since value of the variable `runWithOidcParameter` and  `useSslParameter` should only be true or false. Any other value cannot be assigned to it and I think should cause a referencing error as it should "technically" be undefined.

That being said, there isn't any rule to this that I could find. So I can put whatever everyone agrees to correct. Thoughts?

Comment (peternied) [reply lib/ci-stack.ts:45]: Found it https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError

Doesn't seem correct, just use `Error` the intent isn't that someone catches it and you included the needed details so it can be remediated

**Review by peternied — APPROVED** [review]

File: lib/ci-stack.ts [hunk 4]
```diff
@@ -33,19 +33,31 @@ export class CIStack extends Stack {
       },
     });
 
-    const useSslParameter = new CfnParameter(this, 'useSsl', {
-      description: 'If the jenkins instance should be access via SSL',
-      allowedValues: ['true', 'false'],
+    const useSslParameter = this.node.tryGetContext('useSsl');
+    if (useSslParameter !== 'true' && useSslParameter !== 'false') {
+      throw new Error('useSsl parameter is required to be set as "true" or "false"');
```
Comment (gaiksaya) [inline lib/ci-stack.ts:38]: Still see the quotes :) Please remove it. Errors are important and need to be clear

File: lib/ci-stack.ts [hunk 5]
```diff
@@ -33,19 +33,31 @@ export class CIStack extends Stack {
...
+    }
 
-    });
+    const useSsl = useSslParameter === 'true';
+
+    const runWithOidcParameter = this.node.tryGetContext('runWithOidc');
+    if (runWithOidcParameter !== 'true' && runWithOidcParameter !== 'false') {
+      throw new Error('runWithOidc parameter is required to be set as "true" or "false"');
```
Comment (gaiksaya) [inline lib/ci-stack.ts:45]: Same as above

**Review by peternied — APPROVED** [review]

**Review by gaiksaya — APPROVED** [review]
