### PR TITLE
Dockerize the jenkins installation

### LINKED ISSUE #56: [Bug] Jenkins doesn't startup
Looks like a version update of jenkins is needed as some plugins are not longer working after the log4j security vulnerability.

From my dev stacks `/var/log/jenkins/jenkins.log`
```
Running from: /usr/lib/jenkins/jenkins.war
2022-01-27 00:11:34.261+0000 [id=1]     WARNING winstone.Logger#logInternal: Parameter handlerCountMax is now deprecated
2022-01-27 00:11:34.274+0000 [id=1]     WARNING winstone.Logger#logInternal: Parameter handlerCountMaxIdle is now deprecated
2022-01-27 00:11:34.278+0000 [id=1]     INFO    org.eclipse.jetty.util.log.Log#initialized: Logging initialized @308ms to org.eclipse.jetty.util.log.JavaUtilLog
2022-01-27 00:11:34.317+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
java.lang.SecurityException: class "Log4jHotPatch"'s signer information does not match signer information of other classes in the same package
        at java.lang.ClassLoader.checkCerts(ClassLoader.java:891)
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
2022-01-27 00:11:35.233+0000 [id=1]     WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2022-01-27 00:11:35.273+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-9.4.33.v20201020; built: 2020-10-20T23:39:24.803Z; git: 1be68755656cef678b79a2ef1c2ebbca99e25420; jvm 1.8.0_312-b07
2022-01-27 00:11:35.463+0000 [id=1]     INFO    o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2022-01-27 00:11:35.487+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2022-01-27 00:11:35.488+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2022-01-27 00:11:35.488+0000 [id=1]     INFO    o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 660000ms
2022-01-27 00:11:35.719+0000 [id=1]     INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/lib/jenkins found at: SystemProperties.getProperty("JENKINS_HOME")
2022-01-27 00:11:35.782+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started w.@3aacf32a{Jenkins v2.263.4,/,file:///var/cache/jenkins/war/,AVAILABLE}{/var/cache/jenkins/war}
```

### LINKED ISSUE #106: [Bug]: Jenkins plugins compability issue
### Describe the bug

Suddenly (04/15/22 around 5PM PST)  plugins installations started failing with below error:
```
022-04-15 02:37:25.111+0000 [id=42]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Token Macro Plugin v270.v8c2ce50dc4fc (token-macro)
java.io.IOException: Failed to load: Token Macro Plugin (270.v8c2ce50dc4fc)
 - Jenkins (2.277.1) or higher required
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:549)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2022-04-15 02:37:25.112+0000 [id=42]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Folders Plugin v6.714.v79e858ef76a_2 (cloudbees-folder)
java.io.IOException: Failed to load: Folders Plugin (6.714.v79e858ef76a_2)
 - Jenkins (2.277.1) or higher required
 ```

Also on UI seeing below:
image

### To reproduce

Try deploying jenkins with this repo's code base. It throw error as above. 
Try installing without any plugins and then install plugins using plugin manager on UI, you will see above image error

### Expected behavior

Jenkins should install and deploy all plugins

### Host / Environment

_No response_

### Additional context

Looks like a bug https://issues.jenkins.io/browse/JENKINS-44377?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel but not sure why it suddenly started failing and not before

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by gaiksaya**
### Description
Dockerize the jenkins installation using plugins pre-baked in the image. 
 
### Issues Resolved
closes  #106 #91 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: lib/compute/jenkins-main-node.ts [hunk 1]
```diff
@@ -360,72 +345,39 @@ export class JenkinsMainNode {
...
+        ? `mkdir /var/lib/jenkins && mount -t efs ${efsId} /var/lib/jenkins`
+        : 'echo Data rentention is disabled, not mounting efs'),
+
+      InitFile.fromFileInline('/docker-compose.yml', join(__dirname, '../../resources/docker-compose.yml')),
+      InitCommand.shellCommand('systemctl start docker && docker-compose up -d'),
 
       // Commands are fired one after the other but it does not wait for the command to complete.
       // Therefore, sleep 60 seconds to wait for jenkins to start
-      // This allows jenkins to generate the secrets files used for auth in jenkins-cli APIs
       InitCommand.shellCommand('sleep 60'),
```
Comment (abhinavGupta16) [inline lib/compute/jenkins-main-node.ts:362]: given we have removed the commands, do we need the `sleep 60`?

Comment (abhinavGupta16) [inline lib/compute/jenkins-main-node.ts:362]: given we have removed the commands, do we need the sleep 60?

File: resources/baseJenkins.yaml [hunk 2]
```diff
@@ -100,7 +87,7 @@ unclassified:
         showMatrixStatus: false
     githubAuth:
     - description: "Anonymous connection"
-      id: "fe7046c5-29a0-4370-b32d-47aead7c5945"
+      id: "d4456c70-9c5e-4b40-bee4-e1ebb693153b"
```
Comment (abhinavGupta16) [inline resources/baseJenkins.yaml:90]: Is this value constant?

File: lib/compute/jenkins-main-node.ts (hunk 1 above)
Comment (gaiksaya) [reply lib/compute/jenkins-main-node.ts:362]: Yes to let jenkins come up via container

File: resources/baseJenkins.yaml (hunk 2 above)
Comment (gaiksaya) [reply resources/baseJenkins.yaml:90]: I think its random, not affecting though.

Comment (abhinavGupta16) [reply resources/baseJenkins.yaml:90]: I think we should then add a comment here for it, since it seems like this is not the first time it would be changing.

**Review by abhinavGupta16 — APPROVED** [review]
LGTM!
