### PR TITLE
Remove deprecated plugins

### LINKED ISSUE #56: [Bug] Jenkins doesn't startup
Looks like a version update of jenkins is needed as some plugins are not longer working after the log4j security vulnerability.

From my dev stacks `/var/log/jenkins/jenkins.log`
```
Running from: /usr/lib/jenkins/jenkins.war
2022-01-27 00:11:34.261+0000 [id=1]     WARNING winstone.Logger#logInternal: Parameter handlerCountMax is now deprecated
2022-01-27 00:11:34.274+0000 [id=1]     WARNING winstone.Logger#logInternal: Parameter handlerCountMaxIdle is now deprecated
2022-01-27 00:11:34.278+0000 [id=1]     INFO    org.eclipse.jetty.util.log.Log#initialized: Logging initialized @308ms to org.eclipse.jetty.util.log.JavaUtilLog
2022-01-27 00:11:34.317+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
java.lang.SecurityException: class "Log4jHotPatch"'s signer information does not match signer information of other classes in the same package
        at java.lang.ClassLoader.checkCerts(ClassLoader.java:891)
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
2022-01-27 00:11:35.233+0000 [id=1]     WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2022-01-27 00:11:35.273+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-9.4.33.v20201020; built: 2020-10-20T23:39:24.803Z; git: 1be68755656cef678b79a2ef1c2ebbca99e25420; jvm 1.8.0_312-b07
2022-01-27 00:11:35.463+0000 [id=1]     INFO    o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2022-01-27 00:11:35.487+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2022-01-27 00:11:35.488+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2022-01-27 00:11:35.488+0000 [id=1]     INFO    o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 660000ms
2022-01-27 00:11:35.719+0000 [id=1]     INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/lib/jenkins found at: SystemProperties.getProperty("JENKINS_HOME")
2022-01-27 00:11:35.782+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started w.@3aacf32a{Jenkins v2.263.4,/,file:///var/cache/jenkins/war/,AVAILABLE}{/var/cache/jenkins/war}
```

### PR DESCRIPTION
**Pull request by peternied**
### Description
Removes depreciated plugins and granularize the installation of the plugins into smaller groups.
 
### Issues Resolved
- Resolves #56  

### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: lib/compute/jenkins-main-node.ts [hunk 1]
```diff
@@ -361,6 +360,22 @@ export class JenkinsMainNode {
...
+    const pluginInstallBlockSize = 10;
+    const jenkinsCliCommand = `java -jar /jenkins-cli.jar -s http://localhost:8080 -auth @${JenkinsMainNode.JENKINS_DEFAULT_ID_PASS_PATH}`;
+    const pluginListCopy = Object.assign([], pluginList);
+    const pluginListSlices: String[] = [];
+    do {
+      pluginListSlices.push(pluginListCopy.splice(0, pluginInstallBlockSize).join(' '));
+    } while (pluginListCopy.length !== 0);
+
+    return pluginListSlices.map((slice, index) => {
+      const extraCommand = (index === pluginListSlices.length - 1) ? `${jenkinsCliCommand} restart` : '';
```
Comment (peterzhuamazon) [inline lib/compute/jenkins-main-node.ts:374]: Can you explain why a restart is needed?

File: lib/compute/jenkins-main-node.ts [hunk 2]
```diff
@@ -330,8 +330,7 @@ export class JenkinsMainNode {
 
       // install all the list of plugins from the list and restart (done in same command as restart is to be done after completion of install-plugin)
       // eslint-disable-next-line max-len
-      InitCommand.shellCommand(`java -jar /jenkins-cli.jar -s http://localhost:8080 -auth @${JenkinsMainNode.JENKINS_DEFAULT_ID_PASS_PATH} install-plugin ${JenkinsPlugins.plugins.join(' ')} `
-      + ` && java -jar jenkins-cli.jar -s http://localhost:8080 -auth @${JenkinsMainNode.JENKINS_DEFAULT_ID_PASS_PATH} restart`),
+      ...JenkinsMainNode.createPluginInstallCommands(JenkinsPlugins.plugins),
```
Comment (peterzhuamazon) [inline lib/compute/jenkins-main-node.ts:333]: How to understand this leading up triple dot?
I only used it in arguments or arrays, not leading up to a call.

File: lib/compute/jenkins-plugins.ts [hunk 3]
```diff
@@ -117,14 +117,11 @@ export class JenkinsPlugins {
...
       'resource-disposer',
       'role-strategy',
-      'ruby-runtime',
-      'rvm',
       's3',
       'saml',
       'scm-api',
       'script-security',
       'simple-theme-plugin',
-      'singleuseslave',
```
Comment (peterzhuamazon) [inline lib/compute/jenkins-plugins.ts:127]: This is being used for security review.

File: test/compute/jenkins-main-node.test.ts [hunk 4]
```diff
@@ -23,7 +23,7 @@ describe('JenkinsMainNode Config Elements', () => {
 
   // THEN
   test('Config elements expected counts', async () => {
-    expect(configElements.filter((e) => e.elementType === 'COMMAND')).toHaveLength(21);
+    expect(configElements.filter((e) => e.elementType === 'COMMAND')).toHaveLength(34);
```
Comment (peterzhuamazon) [inline test/compute/jenkins-main-node.test.ts:26]: Why is this length increased here?

File: lib/compute/jenkins-main-node.ts (hunk 1 above)
Comment (peternied) [reply lib/compute/jenkins-main-node.ts:374]: After all the plugins are installed jenkins is restarted, this was done before on line 334, which was removed

File: lib/compute/jenkins-main-node.ts (hunk 2 above)
Comment (peternied) [reply lib/compute/jenkins-main-node.ts:333]: It expands array into individual elements, which are composed into an array returned by the `configElements` function

Check out this stackoverflow comment that provide more context https://stackoverflow.com/a/61683996

File: test/compute/jenkins-main-node.test.ts (hunk 4 above)
Comment (peternied) [reply test/compute/jenkins-main-node.test.ts:26]: Previously we installed the plugins all at once, now I 'spread' out the number of plugins installed at a time to 10 each, adding 13 additional 'install-plugin' cli commands to be run.

File: lib/compute/jenkins-plugins.ts (hunk 3 above)
Comment (peternied) [reply lib/compute/jenkins-plugins.ts:127]: Per the notice, https://www.jenkins.io/blog/2021/12/22/deprecated-ruby-runtime/.  We have switched to using disposable docker agents instead of disposable nodes from the previous iteration
```
Single Use Agent
Last released 7 years ago.
Suggestion: Use cloud agents (Fargate, Azure Container Instances, Docker, etc.) to allocate agents for a single use and then release them.
```

File: lib/compute/jenkins-main-node.ts (hunk 2 above)
Comment (peternied) [reply lib/compute/jenkins-main-node.ts:333]: You can play around with it in your browser's console, these arrays are all the same. 
```javascript
[1, 2, 3, 4] == [1, ...[2, 3], 4] == [1, ...[2, ...[3]], 4]
```

File: lib/compute/jenkins-main-node.ts (hunk 1 above)
Comment (peterzhuamazon) [reply lib/compute/jenkins-main-node.ts:374]: Got it.

File: lib/compute/jenkins-main-node.ts (hunk 2 above)
Comment (peterzhuamazon) [reply lib/compute/jenkins-main-node.ts:333]: I got that, but why is it spreading on JenkinsMainNode?
I can understand if this is spread on plugins list.
But mainnode is only having one entry, right?

File: lib/compute/jenkins-plugins.ts (hunk 3 above)
Comment (peterzhuamazon) [reply lib/compute/jenkins-plugins.ts:127]: Security has previous reject my opinion on removing docker node, stating removing agent is much safer option, hence I ask.

File: test/compute/jenkins-main-node.test.ts (hunk 4 above)
Comment (peterzhuamazon) [reply test/compute/jenkins-main-node.test.ts:26]: Got It.

**Review by gaiksaya — APPROVED** [review]
Thanks for resolving this.
I cloned your branch and tried deploying the jenkins, after entering the initial password it asked to install plugins. I installed clicked `install recommended plugins`. While doing so I saw workspace cleanup plugin failed to install. I proceeded and later saw that plugin in installed section. Maybe a transient issue, Just wanted to know if you faced the same?

Also are we planning to upgrade the jenkins version: https://www.jenkins.io/changelog/
Looks like many security and bug fixes have been fixed in new versions.

File: lib/compute/jenkins-plugins.ts (hunk 3 above)
Comment (gaiksaya) [reply lib/compute/jenkins-plugins.ts:127]: Plugin distribution has been suspended for these plugins. Example: https://plugins.jenkins.io/singleuseslave/

File: lib/compute/jenkins-main-node.ts (hunk 2 above)
Comment (peternied) [reply lib/compute/jenkins-main-node.ts:333]: This behavior is verified with `test/compute/jenkins-main-node.test.ts` updates

**Comment by abhinavGupta16** [comment]
> Thanks for resolving this. I cloned your branch and tried deploying the jenkins, after entering the initial password it asked to install plugins. I installed clicked `install recommended plugins`. While doing so I saw workspace cleanup plugin failed to install. I proceeded and later saw that plugin in installed section. Maybe a transient issue, Just wanted to know if you faced the same?
> 
> Also are we planning to upgrade the jenkins version: https://www.jenkins.io/changelog/ Looks like many security and bug fixes have been fixed in new versions.

I think we should update the jenkins version. @peterzhuamazon - thoughts?

**Comment by peternied** [comment]
> > Thanks for resolving this. I cloned your branch and tried deploying the jenkins, after entering the initial password it asked to install plugins. I installed clicked `install recommended plugins`. While doing so I saw workspace cleanup plugin failed to install. I proceeded and later saw that plugin in installed section. Maybe a transient issue, Just wanted to know if you faced the same?
> > Also are we planning to upgrade the jenkins version: https://www.jenkins.io/changelog/ Looks like many security and bug fixes have been fixed in new versions.
> 
> I think we should update the jenkins version. @peterzhuamazon - thoughts?

Lets do that separately so we can merge this PR

**Review by abhinavGupta16 — APPROVED** [review]
Looks good to me
