### PR TITLE
Load balancer changes for http to https redirection

### LINKED ISSUE #68: [Bug]: Http doesnot auto redirect to https when SSL is enabled
### Describe the bug

http://url should auto redirect to https when SSL is enabled. 
currently it does not. 

Need to change this line to http:// https://github.com/opensearch-project/opensearch-ci/blob/main/lib/compute/jenkins-main-node.ts#L222

### To reproduce

Deploy the cluster using ssl enabled and try http://url. It hangs up
where as https://url works.

### Expected behavior

Http should redirect to https automatically

### Host / Environment

_No response_

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

### Description
After #69 the issue for redirection still existed. This change fixes that.
Deployed the stack with self signed certs and tried http://url. It auto-redirected to https
 
### Issues Resolved
Resolves #68 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: lib/network/ci-external-load-balancer.ts [hunk 1]
```diff
@@ -41,11 +42,21 @@ export class JenkinsExternalLoadBalancer {
     const accessPort = props.useSsl ? 443 : 80;
 
     this.listener = this.loadBalancer.addListener('JenkinsListener', {
+      sslPolicy: SslPolicy.RECOMMENDED,
```
Comment (peterzhuamazon) [inline lib/network/ci-external-load-balancer.ts:45]: What is        sslPolicy: SslPolicy.RECOMMENDED?
Can you specifically define it to TLS1-2-2017-01?

Comment (gaiksaya) [reply lib/network/ci-external-load-balancer.ts:45]: CDK recommends which works best for our set up. Hence keeping it that way.

Comment (gaiksaya) [reply lib/network/ci-external-load-balancer.ts:45]: More details: https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-elasticloadbalancingv2.SslPolicy.html

Comment (peterzhuamazon) [reply lib/network/ci-external-load-balancer.ts:45]: We get approved specifically for 2017 one, please do not use CDK recommended one and use the tls 1 2 2017 01 specifically.

Comment (peterzhuamazon) [reply lib/network/ci-external-load-balancer.ts:45]: Thanks.

Comment (gaiksaya) [reply lib/network/ci-external-load-balancer.ts]: Changed and tested! Thanks!

**Review by abhinavGupta16 — APPROVED** [review]

File: lib/network/ci-external-load-balancer.ts (hunk 1 above)
Comment (peterzhuamazon) [reply lib/network/ci-external-load-balancer.ts]: Nitpik, add a comment to state that ` TLS12 = 'ELBSecurityPolicy-TLS-1-2-2017-01'`

Comment (gaiksaya) [reply lib/network/ci-external-load-balancer.ts]: You can see that if you click on the enum value from IDE.

Comment (peterzhuamazon) [reply lib/network/ci-external-load-balancer.ts]: That is not good enough for code reviewing, but ok.

Comment (peterzhuamazon) [reply lib/network/ci-external-load-balancer.ts]: I just want to code to be more clear without additional tools.

**Review by peterzhuamazon — APPROVED** [review]
